name: Build and test

on:
    push:
        branches:
            - '**'
            - '!main'
    pull_request:
        branches:
            - '**'
            - '!main'

jobs:
    pass-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [23.5.0]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Run unit tests
              run: npm test --workspaces

            # - name: Run cypress tests
            #   run: |
            #          npm run dev &
            #          PID=$!
            #          npm run test:cypress:run
            #          kill $PID

            - name: Create build
              run: npm run build --workspaces

            - uses: actions/upload-artifact@v4
              with:
                  name: mandelbrot-core
                  path: packages/mandelbrot-core/dist/

            - uses: actions/upload-artifact@v4
              with:
                  name: react-mandelbrot
                  path: packages/react-mandelbrot/dist/

            - uses: actions/upload-artifact@v4
              with:
                  name: site
                  path: packages/site/dist/
