name: Publish @zazzik/mandelbrot-core to npm

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [23.5.0]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - uses: actions/download-artifact@v4
              with:
                  name: mandelbrot-core
                  path: .

            - name: Publish to npm
              run: |
                  cd packages/mandelbrot-core
                  npm publish
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
